### ISSUE TITLE
Tidy GitHub Repos

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool#251]
@bdon mentioned removing: https://github.com/hotosm/hot-exports

should we also rename repo: osm-export-tool2 to osm-export-tool3?

**Comment by bdon** [comment]
is the "2" distinction important? what about just renaming it to osm-export-tool ?

**Comment by almccon** [comment]
I was also confused. The [blog post](https://www.hotosm.org/updates/2017-09-18_export_tool_30_launched) makes a strong distinction between version 2 and version 3. I was playing with version 3 online, and when I went to check out the repo, I thought maybe I'd been playing with the wrong one the whole time, because the repo I arrived at said `osm-export-tool2`. 

Since this repo contains the v2 and the v3 code, it's probably best to simply remove the "2" from the name, but to add a 3.0.0 release tag, just to make it obvious that this is the "version 3" mentioned prominently in the blog post.

Oh, and by the way, great work everybody!

Also, now the README on `hot-exports` is also confusing, too. :)

**Comment by smit1678** [comment]
Agreed that `osm-export-tool` may be the best way forward. A similar decision was made with the `tasking-manager`.

**Comment by mataharimhairi** [comment]
@bdon agree with both you and Nate. renaming to `osm-export-tool` would make the most sense for current and future development purposes. thanks!

**Comment by mataharimhairi** [comment]
updated the transifex project to reflect this as well: https://www.transifex.com/hotosm/export-tool/dashboard/

**Comment by mojodna** [comment]
I just renamed this to `osm-export-tool` since GitHub will handle redirects from the old URL.

**Comment by mataharimhairi** [comment]
Great. Updated https://github.com/hotosm/hot-exports to https://github.com/hotosm/old-export-tool and changed the link pointing to current repo from https://github.com/hotosm/osm-export-tool2 to https://github.com/hotosm/osm-export-tool.

Not sure we should remove https://github.com/hotosm/old-export-tool just yet. Might wait till end of November for that!
