### ISSUE TITLE
Include land polygons 

### ISSUE THREAD

**Issue by olivierdalang** [hotosm/osm-export-tool#295]
Hi !

One major issue when extracting from OSM is the coastline, because they are a represented as ways in the OSM data structure, while you would need the land masses as polygons to be able to map it correctly.

This makes it very difficult to represent correctly coastal areas, as you need to separately get the land masses polygons

It would be awesome if HOT-OSM exports did the job of including the land polygons cropped to the area of interest.

Thanks !

**Comment by bdon** [comment]
@olivierdalang This may be outside the current Export Tool's capabilities, because in order to create land or sea polygons, all coastline ways in the entire OSM dataset must be pre-processed at once. 

This preprocessed data is already available at https://osmdata.openstreetmap.de , so users of the Export Tool who need land or sea polygons could download the separate dataset from there.

**Comment by bdon** [comment]
I added a link on the docs https://export.hotosm.org/en/v3/learn/quick_start#step4 to osmdata.openstreetmap.de - this data needs to be processed globally and doesn't change that quickly, so downloading it from there is best for most GIS users
