### ISSUE TITLE
Milestone 1. Setup Overpass on own Azure instance

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool#315]

**Comment by mojodna** [comment]
@dakotabenjamin @ramyaragupathy the MM leaderboard deployment will need to be updated when this changes (it currently points at `export.hotosm.org`).

**Comment by bdon** [comment]
Sub-tasks:

- [ ] Set up CloudWatch monitoring for overpass replication state, disk and memory usage. 
- [ ] Switch other HOT applications to new Overpass

@mojodna other than MM Leaderboard, what other applications use Overpass? Is it OK if the only exposed CGI scripts are /interpreter and /augmented_diffs ? Also, I think we'll use HTTP instead of HTTPS for the new instance - the other public instances seem to be fine with HTTP and I don't see our instance being consumed directly from a browser (let me know if you know of otherwise)

**Comment by mojodna** [comment]
Just MM and the occasional augmented diff-related experiment I run on an ad hoc basis.

`/{interpreter,augmented_diff_status,augmented_diff}` please.

I don't know of any browser-based uses.

**Comment by mataharimhairi** [comment]
@bdon notes

> new overpass is running at http://overpass.hotosm.org/api/interpreter - gradually catching up, still about a day behind

**Comment by bdon** [comment]
@mojodna can you try switching to http://overpass.hotosm.org ? it should support those 3 endpoints now.

**Comment by mojodna** [comment]
Working for my ad hoc tests.

@dakotabenjamin / @ramyaragupathy can you change `OVERPASS_URL` in the MM workers, test, and deploy?

**Comment by ramyaragupathy** [comment]
sure @mojodna - we will test this out

**Comment by ramyaragupathy** [comment]
@dakotabenjamin deployed the containers with the updated url. New overpass is about 14 diffs behind the main overpass. Otherwise rest of the updates on the DB is working as expected

**Comment by bdon** [comment]
There's a CloudWatch metric called ReplicationSecondsBehind in the HOT AWS account that tracks how far behind it is - looks like it can spike to around 10-15 minutes behind. I'm comparing this to the previous Overpass instance at export.hotosm.org and it's about the same.

**Comment by willemarcel** [comment]
I noticed the overpass instance doesn't have https enabled. Tracking it here in case it was forgotten.

**Comment by bdon** [comment]
@willemarcel see above https://github.com/hotosm/osm-export-tool/issues/315#issuecomment-509436286
