### ISSUE TITLE
PBF exports not filtered

### ISSUE THREAD

**Issue by Melegy90** [hotosm/osm-export-tool#338]
Hello everyone. Ever since yesterday's temporary halt in the exporting function, the "pbf" exports I'm getting now are unfiltered means that if the export filters out only transportation-->roads data, I still get all linestring data from OSM.

In short, feature filter is no longer working apparently.

**Comment by bdon** [comment]
Hi, thanks for reporting this. I understand what the issue is now :)

Previously, the "PBF" exports were filtered down to the specified tags for performance reasons, with the changes I made yesterday this is no longer necessary. But I understand now that you were relying on this to download a filtered PBF file. What I'll likely do is make the filtered PBF the default and add a checkbox option for unfiltered PBFs.

**Comment by bdon** [comment]
@Melegy90 can you try using http://export-staging.hotosm.org and see if the result filtered PBF is correct like you expect? I have updated that site with the change you requested.

**Comment by Melegy90** [comment]
> @Melegy90 can you try using http://export-staging.hotosm.org and see if the result filtered PBF is correct like you expect? I have updated that site with the change you requested.

Yes thank you Brandon, the staging version works as expected!

**Comment by bdon** [comment]
There is now an "unfiltered" option for PBF files - the default behavior is filtered like before.
